version: "3.8"
services:
  ttyd:
    build:
      context: .
      dockerfile: Dockerfile.ttyd
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    volumes:
      - ./public:/srv/html

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docsify
    ports:
      - "3000:3000"
    volumes:
      - ./docs:/srv/docs
