version: "3.8"
services:
  ttyd:
    build:
      context: .
      dockerfile: Dockerfile.ttyd
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    volumes:
      - ./public:/srv/html


  docsify:
    image: node:18-alpine
    container_name: docsify
    command: sh -c "npm install -g docsify-cli && docsify serve /docs -p 3000"
    working_dir: /docs
    volumes:
      - ./docs:/docs
    ports:
      - "3000:3000"
    restart: unless-stopped