FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64 -o /usr/local/bin/ttyd && \
    chmod +x /usr/local/bin/ttyd

CMD [ "bash", "-c", "nohup ttyd -p 8080 -i 0.0.0.0 --disable-ssl -W bash > /tmp/ttyd.log 2>&1 & tail -f /dev/null" ]
